'use strict';
// build2.cjs — continuation: page generators that use build.cjs exports
// This requires build.cjs to have already run and appended its exports,
// but since we can't easily export from a truncated file, we use a simpler approach:
// This file just appends the rest of build.cjs content when merged by run.cjs

// Contact form HTML (appended to build.cjs CONTACT variable)
const CONTACT_REST = `form bg-white rounded-2xl shadow-lg p-6 md:p-8 space-y-4"><div class="grid grid-cols-1 md:grid-cols-2 gap-4"><div><label class="block text-sm font-bold text-stone-700 mb-1">Name</label><input type="text" name="name" required placeholder="Your name" class="w-full border border-stone-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-red-700"/></div><div><label class="block text-sm font-bold text-stone-700 mb-1">Email</label><input type="email" name="email" required placeholder="your@email.com" class="w-full border border-stone-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-red-700"/></div></div><div><label class="block text-sm font-bold text-stone-700 mb-1">Subject</label><input type="text" name="subject" required placeholder="What's this about?" class="w-full border border-stone-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-red-700"/></div><div><label class="block text-sm font-bold text-stone-700 mb-1">Message</label><textarea name="message" required rows="5" placeholder="Your message..." class="w-full border border-stone-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-red-700 resize-none"></textarea></div><button type="submit" class="btn-submit w-full bg-red-700 hover:bg-red-800 text-white font-bold py-3 rounded-full flex items-center justify-center gap-2 transition-colors"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"/></svg>Send Message</button></form><div class="form-success" style="display:none"><div class="bg-white rounded-2xl shadow-lg p-10 text-center"><svg class="w-14 h-14 text-green-600 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg><h3 class="text-xl font-chunkfive text-stone-900 mb-2">Message Sent!</h3><p class="text-stone-600">Thanks for reaching out. We'll get back to you soon.</p></div></div></div></section>`;

module.exports = { CONTACT_REST };
